#!/usr/bin/env python3
"""Guard against unsupported MRHOF comparisons.

An MRHOF comparison must be generated by an independently implemented
baseline campaign. This project currently contains MARTHR campaigns only;
therefore this script intentionally refuses to manufacture reference values.
"""


def main() -> None:
    raise SystemExit(
        "No MRHOF baseline campaign is available. Run an independently "
        "implemented baseline before producing a comparison."
    )


if __name__ == "__main__":
    main()
